### ISSUE TITLE
toDataURL("image/jpeg") SECURITY ERROR

### ISSUE THREAD

**Issue by Fayozjon** [stepan1010/memeone#1]
Hi!
Your script not working properly in Mozilla
Im getting error

``` javascript
document.getElementById("memeone_created_meme").value = document.getElementById("memeone_canvas").toDataURL("image/jpeg");
```

needed to add

``` javascript
    image.crossOrigin="anonymous";  
```

Please help to solve this problem

**Comment by stepan1010** [comment]
Hello Fayozjon,

Thanks a lot for your comment :)

Could you please elaborate a bit more on the problem? What error exactly are you getting? Which Firefox version do you use? Which OS are you on?

The reason I ask is because I could not recreate the issue and the fix you've provided works for images that are loaded from a remote host. Images in this plugin are either being loaded from the same host (preloaded backgrounds) or by using a FileReader (custom backgrounds) specifically to avoid cross-origin issues.

Cheers,
Stepan

**Comment by Fayozjon** [comment]
Hi @stepan1010 sorry for my late answer.
The issue was providing an images caching service of WP.
Fixed out by turning off this feauture of WP.
